import type { Metadata } from "next";
import "./globals.css";

import { plusJakartaSans, inter, manrope } from './fonts'
import Navbar from "./components/layouts/Navbar";
import Footer from "./components/layouts/Footer";


export const metadata: Metadata = {
  title: "Staffton App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className={`
        ${plusJakartaSans.variable}
        ${inter.variable}
        ${manrope.variable}
      `}
    >
      <body className="min-h-full flex flex-col">

        <Navbar />
        
        {children}

        <Footer />
        
        </body>
    </html>
  );
}
