/**
 * =============================================================================
 * PAGE SEO CONTENT — share this file with the SEO team
 * =============================================================================
 *
 * How to use:
 * 1. Send this file to SEO.
 * 2. SEO updates titles, descriptions, Open Graph copy, and keywords only.
 * 3. Send the file back — drop it in place. No page code changes needed.
 *
 * Do NOT rename keys (home, hireTalent, …).
 * If you change a path, update the matching App Router folder and internal links.
 *
 * Guidelines (title ~50–60 chars, description ~150–160 chars):
 * - Unique title + description per page
 * - Primary keyword near the start of the title
 * - Description: clear value prop + soft CTA
 * - Open Graph title/description can differ slightly (social click appeal)
 * =============================================================================
 */

import type { Metadata } from "next";
import { absoluteUrl, SITE_DESCRIPTION, SITE_NAME, SITE_URL } from "./site";

/**
 * Default social share image (generated by app/opengraph-image.tsx).
 * Must be set on every page — nested routes that override `openGraph`
 * without `images` drop the root file-based og:image.
 */
const OG_IMAGE = {
  // Absolute URL — relative URLs can fail on LinkedIn/WhatsApp/Telegram scrapers
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: "Staffton - Healthcare Hiring Platform for Doctors & Nurses",
  type: "image/png",
} as const;

type PageSeoCopy = {
  /** Browser / SERP title. String uses layout template: "%s | Staffton Health" */
  title: string | { absolute: string };
  description: string;
  /** Optional social title; falls back to title if omitted */
  ogTitle?: string;
  /** Optional social description; falls back to description if omitted */
  ogDescription?: string;
};

const pages = {
  home: {
    path: "/",
    title: {
      absolute: "Healthcare Hiring Platform for Hospitals & Doctors | Staffton",
    },
    description:
      "Staffton is India's healthcare hiring platform connecting hospitals with verified doctors and nurses. Automated credentials, real-time matching, hire in 48h.",
    ogTitle: "Healthcare Hiring Platform for Hospitals & Doctors | Staffton",
    ogDescription:
      "Staffton is India's healthcare hiring platform connecting hospitals with verified doctors and nurses. Automated credentials, real-time matching, hire in 48h.",
  },
  hireTalent: {
    path: "/best-medical-staffing-companies",
    title: {
      absolute: "Best Medical Staffing Companies for Hospitals | Staffton",
    },
    description:
      "Staffton is among the best medical staffing companies in India, helping hospitals hire verified doctors and nurses fast with AI matching and credential checks.",
    ogTitle: "Best Medical Staffing Companies for Hospitals | Staffton",
    ogDescription:
      "Staffton is among the best medical staffing companies in India, helping hospitals hire verified doctors and nurses fast with AI matching and credential checks.",
  },
  forProfessionals: {
    path: "/nurse-doctor-jobs-india",
    title: {
      absolute: "Nurse & Doctor Jobs in India | Get Hired Fast - Staffton",
    },
    description:
      "Explore nurse & doctor jobs in India on Staffton's healthcare job portal. Apply to ICU, ER, OT, pediatric, and oncology roles.",
    ogTitle: "Nurse & Doctor Jobs in India | Get Hired Fast - Staffton",
    ogDescription:
      "Explore nurse & doctor jobs in India on Staffton's healthcare job portal. Apply to ICU, ER, OT, pediatric, and oncology roles.",
  },
  about: {
    path: "/about-us",
    title: "About Staffton Health - Healthcare Recruiting Platform",
    // Trimmed to ≤160 chars (was 161)
    description:
      "Staffton Health is a healthcare hiring platform based in Bangalore, India, connecting 500+ hospitals with 15,000+ verified doctors, nurses and medical staff.",
    // Improved OG copy — more compelling for social shares
    ogTitle: "About Staffton Health | Healthcare Recruitment Platform",
    ogDescription:
      "Staffton Health connects 500+ hospitals with 15,000+ verified doctors and nurses across India. Discover our story and mission.",
  },
  contact: {
    path: "/contact-us",
    title: "Contact Staffton Health - Specialist Recruitment Support",
    description:
      "Get in touch with the Staffton Health team in Bangalore, India. Reach us by email for hospital hiring, healthcare job queries, partnerships and support.",
    // Improved OG copy — action-oriented for social shares
    ogTitle: "Contact Staffton Health | Hire Faster or Get Hired",
    ogDescription:
      "Questions about healthcare hiring or job opportunities? Reach the Staffton Health team in Bangalore. We'll get back within 24 hours.",
  },
  privacyPolicy: {
    path: "/privacy-policy",
    title: "Privacy Policy",
    description:
      "Read the Staffton Health Privacy Policy to understand how we collect, use, store, and protect your personal information, resumes, and credentials.",
    // Added OG copy — was missing entirely (critical fix)
    ogTitle: "Privacy Policy | Staffton Health",
    ogDescription:
      "Understand how Staffton Health collects, uses, and protects your personal information, resumes, and healthcare credentials.",
  },
  termsOfService: {
    path: "/terms-of-service",
    title: "Terms of Service",
    description:
      "Review the Terms of Service for Staffton Health, governing platform eligibility, account registration, credential verification, and acceptable use guidelines.",
    // Added OG copy — was missing entirely (critical fix)
    ogTitle: "Terms of Service | Staffton Health",
    ogDescription:
      "Review the Terms of Service governing your use of the Staffton Health healthcare recruitment platform.",
  },
  cookiePolicy: {
    path: "/cookie-policy",
    title: "Cookie Policy",
    description:
      "Read the Staffton Health Cookie Policy to understand how we use cookies, tracking technologies, and how you can manage your preferences.",
    // Added OG copy — was missing entirely (critical fix)
    ogTitle: "Cookie Policy | Staffton Health",
    ogDescription:
      "Learn how Staffton Health uses cookies and tracking technologies, and how to manage your cookie preferences.",
  },
} as const satisfies Record<string, PageSeoCopy & { path: string }>;

export type PageSeoKey = keyof typeof pages;

/** Site-wide defaults used by app/layout.tsx */
export const siteSeo = {
  defaultTitle: "Staffton - Healthcare Hiring Platform for Doctors & Nurses",
  titleTemplate: "%s | Staffton Health",
  description: SITE_DESCRIPTION,
  keywords: [
    "healthcare hiring platform",
    "medical recruitment India",
    "hire nurses",
    "hire doctors",
    "healthcare jobs India",
    "hospital staffing",
  ],
} as const;

function toMetadata(
  copy: PageSeoCopy & { path: string },
): Metadata {
  const url = absoluteUrl(copy.path);
  const ogTitle =
    copy.ogTitle ??
    (typeof copy.title === "string" ? copy.title : copy.title.absolute);
  const ogDescription = copy.ogDescription ?? copy.description;

  return {
    title: copy.title,
    description: copy.description,
    alternates: {
      canonical: url,
    },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_IN",
      title: ogTitle,
      description: ogDescription,
      url,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      site: "@stafftonhealth",
      title: ogTitle,
      description: ogDescription,
      images: [OG_IMAGE],
    },
  };
}

/** Per-page metadata — import in each page.tsx */
export const pageMetadata = {
  home: toMetadata(pages.home),
  hireTalent: toMetadata(pages.hireTalent),
  forProfessionals: toMetadata(pages.forProfessionals),
  about: toMetadata(pages.about),
  contact: toMetadata(pages.contact),
  privacyPolicy: toMetadata(pages.privacyPolicy),
  termsOfService: toMetadata(pages.termsOfService),
  cookiePolicy: toMetadata(pages.cookiePolicy),
} as const satisfies Record<PageSeoKey, Metadata>;

/** Root layout metadata (metadataBase, OG site defaults, robots, etc.) */
export const rootMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: siteSeo.defaultTitle,
    template: siteSeo.titleTemplate,
  },
  description: siteSeo.description,
  applicationName: SITE_NAME,
  keywords: [...siteSeo.keywords],
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en_IN",
    url: SITE_URL,
    images: [OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    site: "@stafftonhealth",
    images: [OG_IMAGE],
  },
  robots: {
    index: true,
    follow: true,
  },
  verification: {
    google: "OUpBrKv4jjjCIqi3Vd-Tz2Y2m9OAbt5zLR4U2q846zM",
  },
  icons: {
    icon: "/staffton-logo.svg",
    shortcut: "/staffton-logo.svg",
  },
};
