export type JobListing = {
  id: string;
  title: string;
  hospital: string;
  location: string;
  experience: string;
  type: string;
  salary: string;
  skills: string[];
  postedAgo: string;
  role?: "doctor" | "nurse" | "allied" | "technician" | "non-technician" | "non-allied";
  education?: string;
};

export interface RoleInfo {
  id: string;
  label: string;
  plural: string;
  titlePrefix: string;
  descriptionPrefix: string;
}

export function getRoleInfo(roleSlug?: string): RoleInfo | null {
  if (!roleSlug) return null;
  const slug = roleSlug.toLowerCase().trim();
  switch (slug) {
    case "doctor":
      return {
        id: "doctor",
        label: "Doctor",
        plural: "Doctors",
        titlePrefix: "Doctor",
        descriptionPrefix: "verified doctor and physician",
      };
    case "nurse":
      return {
        id: "nurse",
        label: "Nurse",
        plural: "Nurses",
        titlePrefix: "Nurse",
        descriptionPrefix: "verified nursing and staff nurse",
      };
    case "allied":
      return {
        id: "allied",
        label: "Allied",
        plural: "Allied Health Professionals",
        titlePrefix: "Allied Healthcare",
        descriptionPrefix: "verified allied healthcare and clinical support",
      };
    case "technician":
      return {
        id: "technician",
        label: "Technician",
        plural: "Technicians",
        titlePrefix: "Medical Technician",
        descriptionPrefix: "verified medical and laboratory technician",
      };
    case "non-allied":
      return {
        id: "non-allied",
        label: "Non-Allied",
        plural: "Non-Allied Staff",
        titlePrefix: "Non-Allied Healthcare",
        descriptionPrefix: "verified non-allied hospital administration and operational",
      };
    case "non-technician":
      return {
        id: "non-technician",
        label: "Non-Technician",
        plural: "Non-Technician Staff",
        titlePrefix: "Non-Technician Healthcare",
        descriptionPrefix: "verified non-technician hospital support and operational",
      };
    default:
      return null;
  }
}

const JOBS_BY_CITY: Record<string, JobListing[]> = {
  Ahmedabad: [
    // Nurses
    {
      id: "ahmedabad-icu-sterling",
      title: "ICU Staff Nurse",
      hospital: "Sterling Hospital",
      location: "SG Highway",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹25,000-₹40,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "ahmedabad-nicu-apollo",
      title: "NICU Nurse",
      hospital: "Apollo Hospital Ahmedabad",
      location: "Bhat",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹38,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "ahmedabad-ot-hcg",
      title: "OT Nurse",
      hospital: "HCG Cancer Centre",
      location: "Sola",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹28,000-₹45,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Oncology"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "ahmedabad-pediatric-shalby",
      title: "Pediatric/NICU Nurse",
      hospital: "Shalby Hospital",
      location: "SG Road",
      experience: "1-3 yrs",
      type: "Full-time Rotational",
      salary: "₹20,000-₹35,000/mo",
      skills: ["Pediatrics", "NICU", "Vaccination"],
      postedAgo: "Posted 4 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "ahmedabad-ward-zydus",
      title: "Ward Staff Nurse",
      hospital: "Zydus Hospital",
      location: "Thaltej",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹32,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 5 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "ahmedabad-gdn-civil",
      title: "General Duty Staff Nurse",
      hospital: "Civil Hospital Ahmedabad",
      location: "Asarwa",
      experience: "0-2 yrs",
      type: "Full-time",
      salary: "₹16,000-₹28,000/mo",
      skills: ["Patient Care", "Vital Signs", "First Aid"],
      postedAgo: "Posted 1 week ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "ahmedabad-doc-rmo-apollo",
      title: "Resident Medical Officer (RMO - ICU / ER)",
      hospital: "Apollo Hospital Ahmedabad",
      location: "Bhat, SG Highway",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹65,000-₹95,000/mo",
      skills: ["Emergency Care", "ICU Management", "BLS/ACLS", "Patient Triage"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "ahmedabad-doc-cardio-zydus",
      title: "Consultant Cardiologist",
      hospital: "Zydus Hospital",
      location: "Thaltej",
      experience: "3-8 yrs",
      type: "Full-time",
      salary: "₹1,80,000-₹3,20,000/mo",
      skills: ["Interventional Cardiology", "Angiography", "Echocardiography", "CCU"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    {
      id: "ahmedabad-doc-pediatric-shalby",
      title: "Consultant Pediatrician",
      hospital: "Shalby Hospital",
      location: "SG Road",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹1,20,000-₹2,00,000/mo",
      skills: ["NICU", "PICU", "Pediatric Emergency", "Neonatology"],
      postedAgo: "Posted 3 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    {
      id: "ahmedabad-doc-anesthesia-sterling",
      title: "Consultant Anesthesiologist",
      hospital: "Sterling Hospital",
      location: "Memnagar",
      experience: "2-7 yrs",
      type: "Full-time",
      salary: "₹1,40,000-₹2,40,000/mo",
      skills: ["General Anesthesia", "Critical Care", "Epidural", "Pain Management"],
      postedAgo: "Posted 4 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    {
      id: "ahmedabad-doc-general-physician",
      title: "General Physician (OPD & IPD)",
      hospital: "HCG Hospitals",
      location: "Mithakhali",
      experience: "1-5 yrs",
      type: "Full-time",
      salary: "₹80,000-₹1,30,000/mo",
      skills: ["Internal Medicine", "Chronic Disease Mgmt", "Preventive Healthcare"],
      postedAgo: "Posted 5 days ago",
      role: "doctor",
      education: "MBBS",
    },
    // Allied
    {
      id: "ahmedabad-allied-physio-shalby",
      title: "Senior Physiotherapist (Orthopedic & Neuro)",
      hospital: "Shalby Hospital",
      location: "SG Highway",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹30,000-₹48,000/mo",
      skills: ["Post-Op Rehab", "Joint Mobilization", "Neuro-rehabilitation"],
      postedAgo: "Posted 2 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    {
      id: "ahmedabad-allied-pharmacist-apollo",
      title: "Clinical Pharmacist",
      hospital: "Apollo Hospital",
      location: "Bhat",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹24,000-₹38,000/mo",
      skills: ["Medication Dispensing", "Pharmacovigilance", "Inventory Control"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "B.Pharm",
    },
    {
      id: "ahmedabad-allied-dietitian-zydus",
      title: "Clinical Nutritionist & Dietitian",
      hospital: "Zydus Hospital",
      location: "Thaltej",
      experience: "1-3 yrs",
      type: "Full-time",
      salary: "₹25,000-₹40,000/mo",
      skills: ["Therapeutic Diets", "ICU Enteral Nutrition", "Diabetes Diet Care"],
      postedAgo: "Posted 4 days ago",
      role: "allied",
      education: "MS/M.Sc(Science)",
    },
    // Technician
    {
      id: "ahmedabad-tech-ot-sterling",
      title: "Senior OT Technician",
      hospital: "Sterling Hospital",
      location: "SG Highway",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹22,000-₹36,000/mo",
      skills: ["OT Equipment", "Sterilization CSSD", "Surgical Assisting"],
      postedAgo: "Posted 1 day ago",
      role: "technician",
      education: "Diploma",
    },
    {
      id: "ahmedabad-tech-dialysis-zydus",
      title: "Dialysis Technician",
      hospital: "Zydus Hospital",
      location: "Thaltej",
      experience: "1-5 yrs",
      type: "Full-time Rotational",
      salary: "₹20,000-₹34,000/mo",
      skills: ["Hemodialysis", "Dialyzer Reprocessing", "Fistula Cannulation"],
      postedAgo: "Posted 3 days ago",
      role: "technician",
      education: "Diploma",
    },
    {
      id: "ahmedabad-tech-cathlab-apollo",
      title: "Cath Lab Technician",
      hospital: "Apollo Hospital",
      location: "Bhat",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Angiography Support", "Hemodynamic Monitoring", "Radiation Safety"],
      postedAgo: "Posted 5 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "ahmedabad-nontech-frontdesk-shalby",
      title: "Hospital Front Desk & Admission Executive",
      hospital: "Shalby Multi-Specialty Hospital",
      location: "SG Road",
      experience: "1-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹28,000/mo",
      skills: ["Patient Registration", "TPA Coordination", "Hospital CRM"],
      postedAgo: "Posted 2 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
    {
      id: "ahmedabad-nontech-billing-hcg",
      title: "Medical Billing & Insurance Desk Executive",
      hospital: "HCG Cancer Centre",
      location: "Sola",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹22,000-₹35,000/mo",
      skills: ["Cashless Claims", "TPA Processing", "Hospital Billing"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Bengaluru: [
    // Nurses
    {
      id: "bengaluru-icu-manipal",
      title: "ICU Staff Nurse",
      hospital: "Manipal Hospital",
      location: "Old Airport Road",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹28,000-₹45,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "bengaluru-nicu-apollo",
      title: "NICU Nurse",
      hospital: "Apollo Hospitals",
      location: "Bannerghatta",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹24,000-₹40,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "bengaluru-ot-fortis",
      title: "OT Nurse",
      hospital: "Fortis Hospital",
      location: "Bannerghatta Road",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹30,000-₹48,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Scrub Nurse"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "bengaluru-ward-narayana",
      title: "Ward Staff Nurse",
      hospital: "Narayana Health",
      location: "Bommasandra",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹20,000-₹34,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 4 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "bengaluru-doc-rmo-manipal",
      title: "Resident Medical Officer (ICU / Emergency)",
      hospital: "Manipal Hospital",
      location: "Old Airport Road",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹70,000-₹1,05,000/mo",
      skills: ["Emergency Protocols", "ICU Care", "Intubation", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "bengaluru-doc-cardio-narayana",
      title: "Consultant Cardiologist",
      hospital: "Narayana Institute of Cardiac Sciences",
      location: "Bommasandra",
      experience: "3-8 yrs",
      type: "Full-time",
      salary: "₹2,00,000-₹3,50,000/mo",
      skills: ["Cardiac Catheterization", "Echocardiogram", "Coronary Interventions"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    {
      id: "bengaluru-doc-neuro-aster",
      title: "Consultant Neurologist",
      hospital: "Aster CMI Hospital",
      location: "Hebbal",
      experience: "2-7 yrs",
      type: "Full-time",
      salary: "₹1,80,000-₹3,00,000/mo",
      skills: ["Stroke Care", "EEG/EMG", "Epilepsy Management"],
      postedAgo: "Posted 3 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "bengaluru-allied-physio-fortis",
      title: "Senior Physiotherapist (Cardiopulmonary)",
      hospital: "Fortis Hospital",
      location: "Cunningham Road",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹32,000-₹50,000/mo",
      skills: ["Chest Physiotherapy", "Cardio Rehab", "Post-Op Mobilization"],
      postedAgo: "Posted 2 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    // Technician
    {
      id: "bengaluru-tech-radiology-manipal",
      title: "Radiology / MRI / CT Technologist",
      hospital: "Manipal Hospital",
      location: "Whitefield",
      experience: "2-6 yrs",
      type: "Full-time Rotational",
      salary: "₹28,000-₹45,000/mo",
      skills: ["1.5T/3T MRI", "CT Angiography", "PACS Administration"],
      postedAgo: "Posted 3 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "bengaluru-nontech-operations-apollo",
      title: "Hospital Operations Executive",
      hospital: "Apollo Hospitals",
      location: "Jayanagar",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹25,000-₹38,000/mo",
      skills: ["Hospital Workflow", "NABH Documentation", "Quality Compliance"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Mumbai: [
    // Nurses
    {
      id: "mumbai-icu-kokilaben",
      title: "ICU Staff Nurse",
      hospital: "Kokilaben Dhirubhai Ambani Hospital",
      location: "Andheri West",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹32,000-₹50,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "mumbai-nicu-lilavati",
      title: "NICU Nurse",
      hospital: "Lilavati Hospital",
      location: "Bandra",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹28,000-₹44,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "mumbai-ot-hinduja",
      title: "OT Nurse",
      hospital: "P. D. Hinduja Hospital",
      location: "Mahim",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹30,000-₹48,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Oncology"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "mumbai-ward-nanavati",
      title: "Ward Staff Nurse",
      hospital: "Nanavati Max Hospital",
      location: "Vile Parle",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹36,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 5 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "mumbai-doc-rmo-lilavati",
      title: "Resident Medical Officer (ICU / Emergency)",
      hospital: "Lilavati Hospital & Research Centre",
      location: "Bandra West",
      experience: "1-5 yrs",
      type: "Full-time Rotational",
      salary: "₹75,000-₹1,15,000/mo",
      skills: ["Emergency Protocols", "Critical Care", "Arterial Line Insertion"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "mumbai-doc-ortho-kokilaben",
      title: "Consultant Orthopedic Surgeon",
      hospital: "Kokilaben Dhirubhai Ambani Hospital",
      location: "Andheri West",
      experience: "3-9 yrs",
      type: "Full-time",
      salary: "₹2,20,000-₹3,80,000/mo",
      skills: ["Joint Replacement", "Arthroscopy", "Trauma Surgery"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    {
      id: "mumbai-doc-physician-hinduja",
      title: "Consultant General Physician",
      hospital: "P. D. Hinduja Hospital",
      location: "Mahim",
      experience: "2-7 yrs",
      type: "Full-time",
      salary: "₹1,30,000-₹2,20,000/mo",
      skills: ["Internal Medicine", "Infectious Diseases", "Geriatric Care"],
      postedAgo: "Posted 3 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "mumbai-allied-lab-nanavati",
      title: "Medical Lab Technologist (Pathology & Bio-chem)",
      hospital: "Nanavati Max Super Speciality Hospital",
      location: "Vile Parle",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹25,000-₹42,000/mo",
      skills: ["Automated Analyzers", "Histopathology", "Blood Banking"],
      postedAgo: "Posted 2 days ago",
      role: "allied",
      education: "B.Sc",
    },
    // Technician
    {
      id: "mumbai-tech-ot-kokilaben",
      title: "Senior Operation Theatre Technician",
      hospital: "Kokilaben Hospital",
      location: "Andheri West",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹28,000-₹46,000/mo",
      skills: ["Robotic Surgery Setup", "CSSD Sterilization", "Surgical Instrumentation"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "mumbai-nontech-patientcare-lilavati",
      title: "Patient Care Coordinator & Front Office Lead",
      hospital: "Lilavati Hospital",
      location: "Bandra",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹24,000-₹38,000/mo",
      skills: ["VIP Patient Services", "Discharge Desk", "Hospital Communication"],
      postedAgo: "Posted 3 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Pune: [
    // Nurses
    {
      id: "pune-icu-ruby",
      title: "ICU Staff Nurse",
      hospital: "Ruby Hall Clinic",
      location: "Sassoon Road",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹24,000-₹40,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "pune-nicu-jehangir",
      title: "NICU Nurse",
      hospital: "Jehangir Hospital",
      location: "Sassoon Road",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹36,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "pune-ot-deenanath",
      title: "OT Nurse",
      hospital: "Deenanath Mangeshkar Hospital",
      location: "Erandwane",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Scrub Nurse"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "pune-ward-sahyadri",
      title: "Ward Staff Nurse",
      hospital: "Sahyadri Hospital",
      location: "Deccan",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹32,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 4 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "pune-doc-rmo-ruby",
      title: "Resident Medical Officer (ICU / Emergency)",
      hospital: "Ruby Hall Clinic",
      location: "Sassoon Road",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹65,000-₹95,000/mo",
      skills: ["ICU Management", "Emergency Triage", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "pune-doc-pediatric-jehangir",
      title: "Consultant Pediatrician",
      hospital: "Jehangir Hospital",
      location: "Sassoon Road",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹1,20,000-₹1,90,000/mo",
      skills: ["Pediatric Care", "Immunization", "Neonatal Resuscitation"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "pune-allied-physio-sahyadri",
      title: "Neuro & Orthopedic Physiotherapist",
      hospital: "Sahyadri Hospital",
      location: "Deccan",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Stroke Rehab", "Joint Therapy", "Gait Training"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    // Technician
    {
      id: "pune-tech-dialysis-deenanath",
      title: "Dialysis Technician",
      hospital: "Deenanath Mangeshkar Hospital",
      location: "Erandwane",
      experience: "1-5 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹35,000/mo",
      skills: ["Hemodialysis", "RO Plant Maintenance", "Cannulation"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "pune-nontech-desk-ruby",
      title: "Front Desk & Billing Executive",
      hospital: "Ruby Hall Clinic",
      location: "Wanowrie",
      experience: "1-3 yrs",
      type: "Full-time",
      salary: "₹20,000-₹30,000/mo",
      skills: ["Admission Desk", "TPA Processing", "Patient Communication"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Delhi: [
    // Nurses
    {
      id: "delhi-icu-apollo",
      title: "ICU Staff Nurse",
      hospital: "Indraprastha Apollo Hospital",
      location: "Sarita Vihar",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹30,000-₹48,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "delhi-nicu-max",
      title: "NICU Nurse",
      hospital: "Max Super Speciality Hospital",
      location: "Saket",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "delhi-ot-fortis",
      title: "OT Nurse",
      hospital: "Fortis Escorts Heart Institute",
      location: "Okhla",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹28,000-₹46,000/mo",
      skills: ["Perioperative", "Cardiac OT", "BLS/ACLS"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "delhi-ward-gangaram",
      title: "Ward Staff Nurse",
      hospital: "Sir Ganga Ram Hospital",
      location: "Rajinder Nagar",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹20,000-₹34,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 6 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "delhi-doc-rmo-max",
      title: "Resident Medical Officer (Emergency / ICU)",
      hospital: "Max Super Speciality Hospital",
      location: "Saket",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹72,000-₹1,10,000/mo",
      skills: ["Emergency Care", "ICU Management", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "delhi-doc-cardio-fortis",
      title: "Consultant Cardiologist",
      hospital: "Fortis Escorts Heart Institute",
      location: "Okhla",
      experience: "3-8 yrs",
      type: "Full-time",
      salary: "₹2,10,000-₹3,60,000/mo",
      skills: ["Coronary Angioplasty", "Echocardiography", "Heart Failure Management"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "delhi-allied-pharmacist-apollo",
      title: "Senior Hospital Pharmacist",
      hospital: "Indraprastha Apollo Hospital",
      location: "Sarita Vihar",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹28,000-₹44,000/mo",
      skills: ["Clinical Pharmacy", "Drug Interaction Monitoring", "Inventory"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "B.Pharm",
    },
    // Technician
    {
      id: "delhi-tech-cathlab-fortis",
      title: "Cath Lab Technologist",
      hospital: "Fortis Escorts Heart Institute",
      location: "Okhla",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹28,000-₹45,000/mo",
      skills: ["Cardiac Cath Lab", "Angiography Procedure", "Radiation Safety"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "delhi-nontech-tpa-gangaram",
      title: "TPA & Cashless Claims Executive",
      hospital: "Sir Ganga Ram Hospital",
      location: "Rajinder Nagar",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹24,000-₹36,000/mo",
      skills: ["TPA Query Resolution", "Pre-authorization", "Claims Settlement"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Chennai: [
    // Nurses
    {
      id: "chennai-icu-apollo",
      title: "ICU Staff Nurse",
      hospital: "Apollo Hospitals",
      location: "Greams Road",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "chennai-nicu-miot",
      title: "NICU Nurse",
      hospital: "MIOT International",
      location: "Manapakkam",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹38,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "chennai-ot-kauvery",
      title: "OT Nurse",
      hospital: "Kauvery Hospital",
      location: "Alwarpet",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹24,000-₹40,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Scrub Nurse"],
      postedAgo: "Posted 4 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "chennai-ward-ramachandra",
      title: "Ward Staff Nurse",
      hospital: "Sri Ramachandra Medical Centre",
      location: "Porur",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹32,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 5 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "chennai-doc-rmo-apollo",
      title: "Resident Medical Officer (ICU / Wards)",
      hospital: "Apollo Hospitals",
      location: "Greams Road",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹65,000-₹95,000/mo",
      skills: ["Clinical Assessment", "Emergency Resuscitation", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "chennai-doc-cardio-kauvery",
      title: "Consultant Cardiologist",
      hospital: "Kauvery Hospital",
      location: "Alwarpet",
      experience: "3-8 yrs",
      type: "Full-time",
      salary: "₹1,90,000-₹3,30,000/mo",
      skills: ["Non-Invasive Cardiology", "Echocardiography", "Coronary Care"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "chennai-allied-physio-miot",
      title: "Senior Physiotherapist (Trauma & Ortho)",
      hospital: "MIOT International",
      location: "Manapakkam",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹28,000-₹45,000/mo",
      skills: ["Trauma Rehab", "Gait Retraining", "Joint Mobilization"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    // Technician
    {
      id: "chennai-tech-ot-apollo",
      title: "Operation Theatre Technician",
      hospital: "Apollo Hospitals",
      location: "Greams Road",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹24,000-₹38,000/mo",
      skills: ["OT Preparation", "Sterilization CSSD", "Surgical Assist"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "chennai-nontech-admin-ramachandra",
      title: "Hospital Front Desk & Admission Officer",
      hospital: "Sri Ramachandra Medical Centre",
      location: "Porur",
      experience: "1-3 yrs",
      type: "Full-time",
      salary: "₹20,000-₹30,000/mo",
      skills: ["Patient Admission", "HIS Software", "Enquiry Handling"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Indore: [
    // Nurses
    {
      id: "indore-icu-bombay",
      title: "ICU Staff Nurse",
      hospital: "Bombay Hospital",
      location: "Scheme 94",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹36,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "indore-nicu-choithram",
      title: "NICU Nurse",
      hospital: "Choithram Hospital",
      location: "Manik Bagh",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹20,000-₹34,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "indore-ot-apollo",
      title: "OT Nurse",
      hospital: "Apollo Hospitals",
      location: "Scheme 74",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹24,000-₹38,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Scrub Nurse"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "indore-ward-chl",
      title: "Ward Staff Nurse",
      hospital: "CHL Hospitals",
      location: "AB Road",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹16,000-₹28,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 1 week ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "indore-doc-rmo-bombay",
      title: "Resident Medical Officer (ICU / Casual)",
      hospital: "Bombay Hospital",
      location: "Scheme 94",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹55,000-₹85,000/mo",
      skills: ["Casualty Care", "ICU Management", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "indore-doc-pediatric-choithram",
      title: "Consultant Pediatrician",
      hospital: "Choithram Hospital & Research Centre",
      location: "Manik Bagh",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹1,10,000-₹1,80,000/mo",
      skills: ["Pediatrics", "Neonatal Care", "Inpatient Rounds"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "indore-allied-physio-chl",
      title: "Physiotherapist (Orthopedic & Sports Rehab)",
      hospital: "CHL Hospitals",
      location: "AB Road",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹22,000-₹36,000/mo",
      skills: ["Joint Therapy", "Post-Surgical Mobilization", "Traction"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    // Technician
    {
      id: "indore-tech-dialysis-bombay",
      title: "Dialysis Technician",
      hospital: "Bombay Hospital",
      location: "Scheme 94",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹18,000-₹30,000/mo",
      skills: ["Hemodialysis Operations", "Cannulation", "Sterilization"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "indore-nontech-frontdesk-apollo",
      title: "Hospital Reception & Patient Coordinator",
      hospital: "Apollo Hospitals",
      location: "Scheme 74",
      experience: "1-3 yrs",
      type: "Full-time",
      salary: "₹16,000-₹26,000/mo",
      skills: ["Enquiry Handling", "OPD Billing", "Doctor Scheduling"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Hyderabad: [
    // Nurses
    {
      id: "hyderabad-icu-apollo",
      title: "ICU Staff Nurse",
      hospital: "Apollo Hospitals",
      location: "Jubilee Hills",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "hyderabad-nicu-yashoda",
      title: "NICU Nurse",
      hospital: "Yashoda Hospitals",
      location: "Secunderabad",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹38,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "hyderabad-ot-aig",
      title: "OT Nurse",
      hospital: "AIG Hospitals",
      location: "Gachibowli",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹28,000-₹45,000/mo",
      skills: ["Perioperative", "Sterile Technique", "GI Surgery"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "hyderabad-ward-kims",
      title: "Ward Staff Nurse",
      hospital: "KIMS Hospitals",
      location: "Secunderabad",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹32,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 5 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "hyderabad-doc-rmo-aig",
      title: "Resident Medical Officer (ICU / Gastro)",
      hospital: "AIG Hospitals",
      location: "Gachibowli",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹70,000-₹1,00,000/mo",
      skills: ["Emergency Protocols", "GI Critical Care", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "hyderabad-doc-neuro-kims",
      title: "Consultant Neurologist",
      hospital: "KIMS Hospitals",
      location: "Secunderabad",
      experience: "3-8 yrs",
      type: "Full-time",
      salary: "₹1,80,000-₹3,20,000/mo",
      skills: ["Neuro ICU", "Stroke Interventions", "Electrophysiology"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "hyderabad-allied-pharmacist-yashoda",
      title: "Clinical Pharmacist",
      hospital: "Yashoda Hospitals",
      location: "Somajiguda",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹25,000-₹40,000/mo",
      skills: ["Inpatient Pharmacy", "Prescription Review", "Medication Auditing"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "B.Pharm",
    },
    // Technician
    {
      id: "hyderabad-tech-radiology-apollo",
      title: "CT / MRI Technologist",
      hospital: "Apollo Hospitals",
      location: "Jubilee Hills",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹26,000-₹42,000/mo",
      skills: ["3T MRI Scanning", "Contrast CT", "Image Processing"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "hyderabad-nontech-tpa-aig",
      title: "Hospital Billing & Insurance Desk Officer",
      hospital: "AIG Hospitals",
      location: "Gachibowli",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹24,000-₹36,000/mo",
      skills: ["Cashless Claims", "TPA Processing", "Discharge Coordination"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
  Kolkata: [
    // Nurses
    {
      id: "kolkata-icu-amri",
      title: "ICU Staff Nurse",
      hospital: "AMRI Hospital",
      location: "Dhakuria",
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹24,000-₹40,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "kolkata-nicu-apollo",
      title: "NICU Nurse",
      hospital: "Apollo Multispeciality Hospital",
      location: "Canal Circular Road",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹22,000-₹36,000/mo",
      skills: ["Neonatal Care", "Phototherapy", "NRP"],
      postedAgo: "Posted 1 day ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: "kolkata-ot-fortis",
      title: "OT Nurse",
      hospital: "Fortis Hospital",
      location: "Anandapur",
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Perioperative", "Sterile Technique", "Scrub Nurse"],
      postedAgo: "Posted 4 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: "kolkata-ward-woodlands",
      title: "Ward Staff Nurse",
      hospital: "Woodlands Hospital",
      location: "Alipore",
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹30,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 6 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Doctors
    {
      id: "kolkata-doc-rmo-apollo",
      title: "Resident Medical Officer (ICU / Emergency)",
      hospital: "Apollo Multispeciality Hospital",
      location: "Canal Circular Road",
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹65,000-₹92,000/mo",
      skills: ["Emergency Triage", "ICU Support", "BLS/ACLS"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: "kolkata-doc-cardio-fortis",
      title: "Consultant Cardiologist",
      hospital: "Fortis Hospital",
      location: "Anandapur",
      experience: "3-8 yrs",
      type: "Full-time",
      salary: "₹1,80,000-₹3,10,000/mo",
      skills: ["Echocardiogram", "Clinical Cardiology", "Cath Lab Assist"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Allied
    {
      id: "kolkata-allied-physio-woodlands",
      title: "Senior Physiotherapist (Cardio-Pulmonary)",
      hospital: "Woodlands Hospital",
      location: "Alipore",
      experience: "2-5 yrs",
      type: "Full-time",
      salary: "₹25,000-₹40,000/mo",
      skills: ["Chest PT", "ICU Early Mobility", "Post-Op Rehab"],
      postedAgo: "Posted 3 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    // Technician
    {
      id: "kolkata-tech-ot-amri",
      title: "Operation Theatre Technician",
      hospital: "AMRI Hospital",
      location: "Dhakuria",
      experience: "1-5 yrs",
      type: "Full-time",
      salary: "₹20,000-₹34,000/mo",
      skills: ["CSSD Sterilization", "Surgical Table Setup", "Anesthesia Assist"],
      postedAgo: "Posted 2 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: "kolkata-nontech-desk-apollo",
      title: "Patient Care Coordinator & Front Desk Lead",
      hospital: "Apollo Multispeciality Hospital",
      location: "Canal Circular Road",
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹18,000-₹28,000/mo",
      skills: ["Hospital Reception", "OPD Queue Management", "Patient Guidance"],
      postedAgo: "Posted 4 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ],
};

function generateGenericCityJobs(city: string, role?: string): JobListing[] {
  const cleanCity = city.charAt(0).toUpperCase() + city.slice(1);
  const baseJobs: JobListing[] = [
    // Doctor
    {
      id: `${cleanCity.toLowerCase()}-doc-rmo-1`,
      title: "Resident Medical Officer (RMO - ICU & ER)",
      hospital: `${cleanCity} Multi-Speciality Hospital`,
      location: `Central ${cleanCity}`,
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹65,000-₹95,000/mo",
      skills: ["Emergency Protocols", "ICU Management", "BLS/ACLS", "Patient Care"],
      postedAgo: "Posted 1 day ago",
      role: "doctor",
      education: "MBBS",
    },
    {
      id: `${cleanCity.toLowerCase()}-doc-physician-1`,
      title: "Consultant General Physician",
      hospital: `Apollo Clinic & Hospital ${cleanCity}`,
      location: `City Medical Corridor, ${cleanCity}`,
      experience: "2-7 yrs",
      type: "Full-time",
      salary: "₹1,20,000-₹2,00,000/mo",
      skills: ["Internal Medicine", "Outpatient Care", "Chronic Care"],
      postedAgo: "Posted 2 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    {
      id: `${cleanCity.toLowerCase()}-doc-pediatric-1`,
      title: "Consultant Pediatrician",
      hospital: `Mother & Child Healthcare Centre ${cleanCity}`,
      location: `Main Road, ${cleanCity}`,
      experience: "2-6 yrs",
      type: "Full-time",
      salary: "₹1,10,000-₹1,90,000/mo",
      skills: ["NICU", "Pediatric Care", "Vaccination"],
      postedAgo: "Posted 3 days ago",
      role: "doctor",
      education: "Any Postgraduate",
    },
    // Nurse
    {
      id: `${cleanCity.toLowerCase()}-nurse-icu-1`,
      title: "ICU Staff Nurse",
      hospital: `${cleanCity} Super Speciality Hospital`,
      location: `Central ${cleanCity}`,
      experience: "2-5 yrs",
      type: "Full-time Rotational",
      salary: "₹25,000-₹40,000/mo",
      skills: ["Critical Care", "Ventilator Mgmt", "BLS/ACLS"],
      postedAgo: "Posted 2 days ago",
      role: "nurse",
      education: "B.Sc",
    },
    {
      id: `${cleanCity.toLowerCase()}-nurse-ot-1`,
      title: "OT Scrub Nurse",
      hospital: `Sterling Surgical Hospital ${cleanCity}`,
      location: `Civil Lines, ${cleanCity}`,
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹24,000-₹38,000/mo",
      skills: ["Sterile Technique", "Scrub Nurse", "CSSD"],
      postedAgo: "Posted 3 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    {
      id: `${cleanCity.toLowerCase()}-nurse-ward-1`,
      title: "Ward Staff Nurse",
      hospital: `City Care Medical Hospital ${cleanCity}`,
      location: `Station Road, ${cleanCity}`,
      experience: "0-3 yrs",
      type: "Full-time Rotational",
      salary: "₹18,000-₹30,000/mo",
      skills: ["Ward Care", "Medication", "Documentation"],
      postedAgo: "Posted 4 days ago",
      role: "nurse",
      education: "GNM / ANM",
    },
    // Allied
    {
      id: `${cleanCity.toLowerCase()}-allied-physio-1`,
      title: "Consultant Physiotherapist",
      hospital: `${cleanCity} Rehabilitation Centre`,
      location: `Ring Road, ${cleanCity}`,
      experience: "1-5 yrs",
      type: "Full-time",
      salary: "₹26,000-₹42,000/mo",
      skills: ["Orthopedic Rehab", "Pain Relief", "Exercise Therapy"],
      postedAgo: "Posted 2 days ago",
      role: "allied",
      education: "Any Graduate",
    },
    {
      id: `${cleanCity.toLowerCase()}-allied-pharma-1`,
      title: "Hospital Clinical Pharmacist",
      hospital: `${cleanCity} Multi-Speciality Hospital`,
      location: `Central ${cleanCity}`,
      experience: "1-3 yrs",
      type: "Full-time",
      salary: "₹22,000-₹35,000/mo",
      skills: ["Medication Dispensing", "Pharmacy Inventory", "Prescription Review"],
      postedAgo: "Posted 4 days ago",
      role: "allied",
      education: "B.Pharm",
    },
    // Technician
    {
      id: `${cleanCity.toLowerCase()}-tech-ot-1`,
      title: "Operation Theatre Technician",
      hospital: `${cleanCity} Surgical Hospital`,
      location: `Civil Lines, ${cleanCity}`,
      experience: "1-4 yrs",
      type: "Full-time",
      salary: "₹20,000-₹34,000/mo",
      skills: ["Surgical Instrument Setup", "CSSD", "Anesthesia Machine Check"],
      postedAgo: "Posted 3 days ago",
      role: "technician",
      education: "Diploma",
    },
    {
      id: `${cleanCity.toLowerCase()}-tech-dialysis-1`,
      title: "Dialysis Technician",
      hospital: `Kidney Care Centre ${cleanCity}`,
      location: `Medical Enclave, ${cleanCity}`,
      experience: "1-4 yrs",
      type: "Full-time Rotational",
      salary: "₹20,000-₹32,000/mo",
      skills: ["Hemodialysis", "Dialyzer Maintenance", "Cannulation"],
      postedAgo: "Posted 5 days ago",
      role: "technician",
      education: "Diploma",
    },
    // Non-Technician
    {
      id: `${cleanCity.toLowerCase()}-nontech-desk-1`,
      title: "Hospital Front Desk & Patient Care Executive",
      hospital: `${cleanCity} Multi-Speciality Hospital`,
      location: `Central ${cleanCity}`,
      experience: "1-3 yrs",
      type: "Full-time",
      salary: "₹18,000-₹28,000/mo",
      skills: ["Patient Admission", "Customer Service", "Billing Coordination"],
      postedAgo: "Posted 3 days ago",
      role: "non-technician",
      education: "Any Graduate",
    },
  ];

  if (!role || role === "all") {
    return baseJobs;
  }
  return baseJobs.filter((job) => {
    if (role === "non-allied" || role === "non-technician") {
      return job.role === "non-allied" || job.role === "non-technician";
    }
    return job.role === role;
  });
}

export function getJobsForCity(city: string, role?: string): JobListing[] {
  // Normalize city key match
  const cityKey = Object.keys(JOBS_BY_CITY).find(
    (k) => k.toLowerCase() === city.toLowerCase().trim()
  );

  const cityListings = cityKey ? JOBS_BY_CITY[cityKey] : generateGenericCityJobs(city);

  if (!role || role === "all") {
    return cityListings;
  }

  const filtered = cityListings.filter((job) => {
    if (role === "non-allied" || role === "non-technician") {
      return job.role === "non-allied" || job.role === "non-technician";
    }
    return job.role === role;
  });
  if (filtered.length > 0) {
    return filtered;
  }

  // If city specific didn't have that role, generate generic fallback for that role
  return generateGenericCityJobs(city, role);
}
